### ISSUE TITLE
Frozen Strings / Line report

### ISSUE THREAD

**Issue by floere** [SamSaffron/memory_profiler#23]
This is run on Ruby 2.2 and 2.3 (same result) using memory_profiler 0.9.4.

I have the following case – see questions at the end.

```
require 'memory_profiler'

GC.start

MemoryProfiler.report do
  h1 = { "key": "value" } # line 6
  h2 = { "key": "value" } # line 7
  
  key = "key" # line 9
  h3 = {}
  h3[key] = "value" # line 11
  key = nil
  
  GC.start
end.pretty_print
```

The "Allocated part ":

```
Allocated String Report
-----------------------------------
         3  "value"
         1  performance/memory/experiments.rb:11
         1  performance/memory/experiments.rb:7
         1  performance/memory/experiments.rb:6

         2  "key"
         1  performance/memory/experiments.rb:11
         1  performance/memory/experiments.rb:9
```

We have three "value" Strings corresponding to the values of the hashes – as expected.
The key part is interesting - Ruby may immediately freeze the Strings here on lines 6 and 7.

```
Retained String Report
-----------------------------------
         1  "key"
         1  performance/memory/experiments.rb:11
```

With the retained String report, I would have expected a single frozen "key" String to show up, originating from line 6, and three "value" Strings, from lines 6, 7, and 11.

- Frozen Strings do not show up – should they?
- Why would the three "value" Strings not be reported?
- And why is the String reported to originate from line 11?

Thanks for any help! :)

**Comment by dgynn** [comment]
Interesting questions. One thing first, the `GC.start` on lines 3 and 14 can be removed. MemoryProfiler  does a full GC before and after the block and disables GC during the block so it can capture all allocations.

The "key" strings in the h1 and h2 hashes are actually being interpreted as symbols rather than Strings. See the difference here when initializing a hash with symbols or strings using hashrocket style.
```ruby
> { "key": "value" }  # original code - creates a symbol key
=> {:key=>"value"} 
> { key: "value" }  # explicitly using a symbol
=> {:key=>"value"} 
> { "key" => "value" } # using hashrocket syntax - creates a string key
=> {"key"=>"value"} 
```

The "value" strings are all correctly not showing up in the retrained Strings report because h1, h2, and h3 are all out-of-scope after the block has been executed. That is also why there are no Hash objects if you look in the "retained objects by class" section. If the h1, h2, h3 variables were defined outside the scope of the block you would see those "value" strings being retained.
```ruby
require 'memory_profiler'

GC.start
h1 = h2 = h3 = nil
MemoryProfiler.report do
  h1 = { "key": "value" } # line 6
  h2 = { "key": "value" } # line 7

  key = "key" # line 9
  h3 = {}
  h3[key] = "value" # line 11
  key = nil

  #GC.start
end.pretty_print
```

Then the most interesting thing is why `"key"` is being retained at all and why on line 11? In the [docs for Hash#[]=](http://ruby-doc.org/core-2.2.2/Hash.html#method-i-5B-5D-3D) it says...
> `key` should not have its value changed while it is in use as a key (an `unfrozen` String passed as a key will be duplicated and frozen).

So it is during the assignment on line 11 that Ruby is allocating and freezing the "key" string. And since it is frozen it is retained after the block completes.

BTW, you might also want to try comparing the differences between `"key".freeze` and `key.freeze` as to how that affects the allocated and retained strings reports.

**Comment by floere** [comment]
@dgynn Excellent response, thanks!

Thanks for the information on MemoryProfiler running GC around the block. I was not aware of that.
The keys on lines 6 and 7 … how derpy of me. Apologies. Thanks for pointing that out and including a nice explanation. Same for the values.

Ah yes, the assignment on line 11 actually creates the frozen String. Thanks!

Also, another good point re `"key".freeze` and `key.freeze` – the former is immediately frozen (a compiler optimization), and subsequent `"key".freeze` will refer to the same object, which won't be the case in the latter, iirc (as opposed to how Symbols operate).

All in all, I now understand much better how MemoryProfiler operates, and the mistakes I made when constructing the case. Thank you, @dgynn, for taking the time to walk me through it.

**Comment by floere** [comment]
I'm closing this, since all questions have been answered perfectly.

**Comment by SamSaffron** [comment]
thanks heaps @dgynn <https://github.com/dgynn>
