### ISSUE TITLE
Profiling live rails apps

### ISSUE THREAD

**Issue by shved** [SamSaffron/memory_profiler#85]
Hi! Im just curious if there is a way to report memory usage on a running rails app (with puma).

I'm thinking of deploying one app instance with memory profiler and route some small amount of arbitrary client calls on it (like 1-5%) to see where the memory goes.

I'm trying to do something like this in my config.ru:

```
require ::File.expand_path('../config/environment', __FILE__)
require 'memory_profiler'

report = MemoryProfiler.report do
  run Rails.application
end

REPDIR = "#{Rails.root}/tmp/memreport".freeze

Dir.mkdir(REPDIR) unless File.exists?(REPDIR)

report_th = Thread.new do
  loop do
    sleep(6.hours.seconds)
    report.pretty_print(scale_bytes:true,to_file:"#{REPDIR}/#{Time.now.to_i}.txt")
  end
end

Signal.trap('INT') do # just for development
  report_th.exit
end
```

But all I've got is some poor info about rack and newrelic middleware and that's all.

Is there a way to do it properly?

**Comment by shved** [comment]
It is obvious not related to how puma works, cause I've just tried similar approach to a Roda app running on a Thin app server. So I'm probalty using memory_profile reporting syntax in a wrong manner.

**Comment by shved** [comment]
Well, I’ve got the point - report is just about run call and not reporting the actual application, which is ok. However question is still standing.

**Comment by SamSaffron** [comment]
Tricky, sampling is going to come at a very high cost.

https://github.com/SamSaffron/memory_profiler/blob/master/lib/memory_profiler/reporter.rb#L43

You would not use a background thread for this, you would do the sampling on the actual thread, introduce middleware that starts and stops at position 0. rack-mini-profiler has a sample report you can use to see how that is done. 

The side effect is that object you allocate during this window and remain allocated would consume a bit more memory due to callsite tracking.
